version: "3"
services:
  selenium-hub:
    image: selenium/hub:3.14.0-arsenic
    container_name: selenium-hub
    ports:
      - "4444:4444"
    environment:
      - GRID_TIMEOUT=60
      - GRID_BROWSER_TIMEOUT=60

  chrome:
    image: selenium/node-chrome:3.14.0-arsenic
    container_name: chrome
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
      - SE_OPTS=-timeout 60 -browserTimeout 60